// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int numOfRandomCalls = Integer.parseInt(args[0]);
		double lessThanHalf = 0;
		double greaterThanHalf = 0;
		
		for (int i = 0; i < numOfRandomCalls; i++) {
			if (Math.random() > 0.5) {
				greaterThanHalf ++;
			}
			else {
				lessThanHalf ++;
			}
		
		}
		
		System.out.println("> 0.5: " + (int) greaterThanHalf + " times");
		System.out.println("<= 0.5: " + (int) lessThanHalf + " times");
		
		if (lessThanHalf > 0) {
			System.out.println("Ratio: " + greaterThanHalf / lessThanHalf);
		}
		else {
			System.out.println("No valid ratio");
		}
	}
}
